version: '3'

services:
  mysqldb:
    container_name: mysqlcontainer
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
      - 3307
    environment:
      MYSQL_DATABASE: mini_project
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password
      DB_NAME: mini_project
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internalnet

  server:
    container_name: nodeappcontainer
    build: 
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      DB_HOST: mysqldb
      DB_USER: admin
      DB_PASSWORD: password123
      DB_NAME: mini_project
      PORT: 3001
    networks:
      - internalnet

  client:
    container_name: reactappcontainer
    build: 
      context: ./client
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001
    ports:
      - "3000:3000"

volumes:
  db-data:

networks:
  internalnet:
    driver: bridge