# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysql
          image: kwokcheong/tic4304_mini_project-mysql:1.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: mini_project
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: password123
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
# NodeJS Express Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: kwokcheong/tic4304_mini_project-server:1.0
---
# NodeJS Express Server Service (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
---
# React Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: kwokcheong/tic4304_mini_project-client:1.0
---
# React Client Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
